#!/usr/bin/env python3
"""Build 30 independently designed lessons, translations and test-only reference programs."""
import json
from pathlib import Path
import re
from advanced_course import CHAPTERS as ADVANCED_CHAPTERS, LESSONS as ADVANCED_LESSONS, advanced_designs

ROOT = Path(__file__).resolve().parents[1]
MARKER = '// Original curriculum — generated by scripts/generate_original_problems.py'
# Retain established identifiers so saved drafts and benchmark histories keep their meaning.
INTRO_IDS = [10001, 10006, 10012, 10017, 10022, 10024, 10051, 10052, 10027, 10030]
CHAPTERS = [
    ('Movement, reuse and recursion', '移动、复用与递归', '移動、再利用と再帰'),
    ('Instructions and composition', '指令参数与组合', '命令引数と組み合わせ'),
]
# Each lesson adds one idea, then revisits it in a different spatial arrangement.
# Two hints move from observation to a strategy; full programs stay in test fixtures.
LESSONS = [
    (('First light', '第一盏灯', '最初の灯り'),
     ('Move one cell forward. The robot starts facing up.', '向前走一格。机器人开始时面向上方。', '一マス前へ進もう。ロボットは最初、上を向いています。'),
     [('The ring is directly ahead of the robot.', '圆环就在机器人的正前方。', '輪はロボットのすぐ前にあります。'),
      ('One s is one forward move.', '一个 s 就是向前走一步。', 's 一つで一歩前に進みます。')]),
    (('Around the block', '绕过石墙', '壁を回り込む'),
     ('Plan a detour around a wall; blocked moves stay in place.', '绕过墙壁规划路线；撞墙时机器人会留在原地。', '壁を回り込もう。壁に向かって進んでも位置は変わりません。'),
     [('The direct route is blocked. Look to the right of the wall.', '直线路线被堵住了，观察墙的右侧。', '直進はできません。壁の右側を見ましょう。'),
      ('Try three segments: right, up, then left.', '把路线分成向右、向上、向左三段。', '右、上、左の三区間に分けてみましょう。')]),
    (('Square stamp', '方形印章', '四角いスタンプ'),
     ('Reuse a side-and-turn procedure four times.', '把走一边再转向的过程重复四次。', '一辺を進んで曲がる手続きを四回使おう。'),
     [('The four sides share one movement pattern.', '四条边共用同一段动作。', '四辺とも同じ動きです。'),
      ('Put the right turn inside the procedure, after the steps.', '把右转放进过程里，接在前进指令后面。', '手続きの中で、歩く命令の後に右回転を入れましょう。')]),
    (('A counted corner', '数得清的拐角', '歩数を決めた角'),
     ('Use a numeric parameter to walk two different distances.', '用数值参数控制两段不同长度的前进。', '数値引数で、長さの違う二区間を歩こう。'),
     [('One segment is seven cells; the other is four.', '一段长七格，另一段长四格。', '一区間は七マス、もう一区間は四マスです。'),
      ('A recursive step counter can subtract 1 until the call is skipped.', '递归计步过程每次减 1，直到参数非正而跳过调用。', '再帰の歩数を毎回 1 減らすと、非正の値で呼び出しが省略されます。')]),
    (('A reusable repeater', '通用重复器', '汎用の繰り返し'),
     ('Combine a repetition count with an instruction parameter.', '把重复次数与指令参数组合起来。', '回数と命令列の引数を組み合わせよう。'),
     [('Use one parameter for six repeats and another for a stair tile.', '一个参数表示重复六次，另一个表示阶梯单元。', '一つの引数を六回の繰り返しに、もう一つを階段の単位に使いましょう。'),
      ('Execute Y, then call the repeater with X-1 and the same Y.', '执行 Y，再用 X-1 和同一个 Y 调用重复器。', 'Y を実行し、X-1 と同じ Y で繰り返しを呼びましょう。')]),
    (('A growing thread', '不断加长的线', '伸び続ける糸'),
     ('Grow an instruction parameter by appending two steps.', '每次在指令参数后追加两步，让路径逐渐增长。', '命令引数の末尾に二歩を足して、道筋を伸ばそう。'),
     [('This spiral turns left and has lengths 2, 4, 6, and so on.', '这条螺旋每次左转，各段长 2、4、6……', 'このらせんは左へ曲がり、長さが 2、4、6……と増えます。'),
      ('Execute X, turn left, then pass Xss into the next call.', '执行 X、左转，再把 Xss 传给下一次调用。', 'X を実行して左へ曲がり、次の呼び出しに Xss を渡しましょう。')]),
    (('Turning rose', '旋转玫瑰', '回るバラ'),
     ('Grow a folded out-and-back instruction and rotate three sizes into four petals.', '让折叠往返的指令逐渐增长，再把三种尺寸旋转成四片花瓣。', '折れた往復命令を伸ばし、三つの大きさを回転して四枚の花びらにしよう。'),
     [('Each folded branch returns to the center with its original heading.', '每条折叠分支都回到中心，并恢复原来的朝向。', '折れた枝は中心へ戻り、元の向きに戻ります。'),
      ('Reuse X six times around the turns, grow X by one step, and rotate the complete three-size motif.', '在转向之间六次复用 X，每层增加一步，再旋转完整的三层图案。', '回転の間に X を六回使い、各段で一歩伸ばし、三段全体を回転させましょう。')]),
    (('Tandem lanterns', '双灯相映', '並ぶ灯籠'),
     ('Compose a counted walk, a fourfold repeater, two lantern frames and their bridge.', '组合计步、四次重复器、两个灯框与连接它们的桥。', '歩数、四回反復、二つの灯籠の枠と橋を組み合わせよう。'),
     [('The two square frames have six-cell sides and share a straight lower bridge.', '两个方框的边长都是六格，底边由直桥连接。', '二つの四角い枠は一辺六マスで、下の直線の橋でつながっています。'),
      ('Make the frame return to its starting pose, then use the counted walker to cross to its twin.', '让灯框过程恢复起点和朝向，再用计步过程走向另一个灯框。', '枠の手続きを元の位置と向きへ戻し、歩数の手続きでもう一つへ渡りましょう。')]),
    (('Woven field', '编织灯田', '織りなす灯り'),
     ('Use a finite row count and alternate the connector’s turn direction.', '用有限的行数控制灯田，并交替改变连接处的转向。', '有限の行数を使い、接続部分の回転方向を交互に変えよう。'),
     [('Each row is eight cells long; safe connectors are at the ends.', '每行长八格，安全的连接处在两端。', '各列は八マスで、安全な接続部分は両端にあります。'),
      ('Adding rr to a turn parameter switches its effective direction.', '给转向参数增加 rr，可以切换它实际的转向方向。', '回転の引数に rr を足すと、実際の回転方向が切り替わります。')]),
    (('Clockwork garden', '发条花园', 'からくりの庭'),
     ('Combine counted repetition, shrinking squares and fourfold rotation.', '组合计数重复、逐渐缩小的正方形与四向旋转。', '回数指定、縮む正方形、四方向の回転を組み合わせよう。'),
     [('Each quadrant contains squares with sides 6, 4 and 2.', '每个象限中都有边长为 6、4、2 的正方形。', '各象限に、辺が 6、4、2 の正方形があります。'),
      ('Build one square, recurse with X-2, then rotate the whole motif.', '先构造一个正方形，再用 X-2 递归，最后旋转整个图案。', '正方形を作って X-2 で再帰し、模様全体を回転させましょう。')]),
]


def s(count):
    return 's' * count


def square(size):
    return (s(size) + 'r') * 4


def trace(start, commands, walls=(), bounded=True):
    x, y = start
    heading = 0
    points = []
    for command in commands:
        if command == 's':
            dx, dy = [(0, -1), (1, 0), (0, 1), (-1, 0)][heading]
            nx, ny = x + dx, y + dy
            if (nx, ny) not in walls:
                if bounded:
                    assert 0 <= nx < 25 and 0 <= ny < 25, (start, nx, ny)
                x, y = nx, ny
            points.append((x, y))
        else:
            heading = (heading + (1 if command == 'r' else -1)) % 4
    return points


def rose_commands():
    return ''.join((s(n)+'r'+s(n)+'l'+s(n)+'rr'+s(n)+'r'+s(n)+'l'+s(n)+'rr') for n in (2, 3, 4))


def walled(start, commands, source):
    from advanced_course import outline
    return (start, commands, source, None, outline(set(trace(start, commands)) | {start}), [])


def designs():
    # Explicit primitive routes provide an independent oracle for the H reference programs.
    return [
        ((12, 13), 's', 's', None, [], []),
        ((12, 14), 'rsslsslss', 'rsslsslss', [(12, 12)], [(11, 13), (12, 13), (13, 13)], []),
        ((10, 17), square(4), 'a:ssssr\naaaa', None, [], []),
        ((8, 20), s(7)+'r'+s(4), 'a(X):sa(X-1)\na(7)ra(4)', None, [], []),
        ((6, 21), 'ssrssl'*6, 'a(X,Y):Ya(X-1,Y)\na(6,ssrssl)', None, [], []),
        ((12, 12), ''.join(s(n)+'l' for n in range(2, 19, 2)), 'a(X):Xla(Xss)\na(ss)', None, [], []),
        walled((12, 12), (rose_commands()+'r')*4,
               'a(N,X):XrXlXrrXrXlXrra(N-1,Xs)\nq(P):PPPP\nq(a(3,ss)r)'),
        walled((4, 15), square(6)+'r'+s(11)+'l'+square(6),
               'b(N):sb(N-1)\nq(P):PPPP\nw:q(b(6)r)\nwrb(11)lw'),
        ((8, 6), 'r'+''.join(s(8)+(('rr'*n+'r')+s(2)+('rr'*n+'r') if n < 4 else '') for n in range(5)),
         'b(X):sb(X-1)\na(X,Y):b(8)Yb(2)Ya(X-1,rrY)\nra(5,r)', None, [],
         [(x, y) for y in range(7, 14, 2) for x in range(9, 16)]),
        ((12, 12), (''.join(square(n) for n in (6, 4, 2))+'r')*4,
         'a(X,Y):Ya(X-1,Y)\nb(X):a(4,a(X,s)r)\nc(X):b(X)c(X-2)\nd:c(6)r\ndddd', None,
         [(x, y) for y in range(5, 20) for x in range(5, 20) if x in (5, 19) or y in (5, 19)],
         [(x, y) for y in range(7, 18, 2) for x in range(7, 18, 2)]),
    ]


def reference_outcome(start, commands, path, targets, traps):
    """Replay the explicit geometric oracle only until its last target is lit."""
    position, heading, lit, blocked, resets = start, 0, set(), 0, 0
    moves = iter(path)
    for steps, command in enumerate(commands, 1):
        if command == 's':
            next_position = next(moves)
            if next_position == position:
                blocked += 1
            else:
                position = next_position
                if position in traps:
                    lit.clear()
                    resets += 1
                if position in targets:
                    lit.add(position)
        else:
            heading = (heading + (1 if command == 'r' else -1)) % 4
        if lit == targets:
            return dict(steps=steps, blocked=blocked, traps=resets,
                        endPosition=list(position), endHeading=heading)
    raise ValueError(f'Geometric oracle did not complete from {start}')


def generate():
    translations = [{} for _ in range(3)]

    def localize(values):
        for language, text in enumerate(values):
            translations[language][values[0]] = text
        return values[0]

    problems, solutions = [], []
    all_lessons = LESSONS + ADVANCED_LESSONS
    all_designs = designs() + advanced_designs(trace)
    all_chapters = CHAPTERS + ADVANCED_CHAPTERS
    assert len(all_lessons) == len(all_designs) == 30
    identifiers = INTRO_IDS + list(range(10031, 10051))
    for position, (index, (title, objective, hints), design) in enumerate(zip(identifiers, all_lessons, all_designs)):

        start, commands, source, targets, walls, traps = design
        path = trace(start, commands, set(walls))
        targets = set(path if targets is None else targets) - {start} - set(traps)
        assert targets and not (set(path) & set(walls))
        assert targets <= set(path) and not (targets & set(walls))
        rows = [['.'] * 25 for _ in range(25)]
        for cells, symbol in [(walls, 'x'), (traps, '*'), (targets, 'o'), ([start], 'u')]:
            for x, y in cells:
                rows[y][x] = symbol
        chapter = position//5
        problems.append(dict(id=index, title=localize(title), author='Herbert',
                             byteLimit=len(re.findall(r'[A-Za-z]|[0-9]+', source)),
                             sourceURL='', sourceSHA256='', rows=[''.join(row) for row in rows],
                             lesson=dict(order=position+1, chapter=chapter+1, chapterTitle=localize(all_chapters[chapter]),
                                         objective=localize(objective), hints=[localize(hint) for hint in hints])))
        solutions.append(dict(id=index, source=source,
                              **reference_outcome(start, commands, path, targets, set(traps))))
    assert len(problems) == 30 and len({tuple(p['rows']) for p in problems}) == 30
    (ROOT/'Sources/HerbertCore/Resources/original-problems.json').write_text(json.dumps(problems, ensure_ascii=False, indent=2)+'\n')
    (ROOT/'Tests/HerbertCoreTests/Fixtures/original-solutions.json').write_text(json.dumps(solutions, indent=2)+'\n')
    for language, values in zip(['en', 'zh-Hans', 'ja'], translations):
        path = ROOT/f'Sources/HerbertCore/Resources/{language}.lproj/Localizable.strings'
        original = path.read_text().split(MARKER)[0].rstrip()
        lines = [f'{json.dumps(k, ensure_ascii=False)} = {json.dumps(v, ensure_ascii=False)};' for k, v in values.items()]
        path.write_text(original+'\n\n'+MARKER+'\n'+'\n'.join(lines)+'\n')
    write_docs(problems)
    print('Generated 30 original lessons, three languages, and test-only reference solutions.')


def write_docs(problems):
    for language, filename in [(0, 'original-course.md'), (1, 'original-course.zh-CN.md')]:
        intro = (
            '# 30 道原创学习关卡\n\n'
            '这套课程依据公开的 H 语言与棋盘规则独立设计，没有把社区棋盘改名或改图后使用。'
            '原创布局、名称、学习目标、提示、生成脚本与参考程序随项目以 MIT 许可发布。\n\n'
            '入门两章共十题：仅前两题可直接逐步写出路线，随后学习复用、递归、指令参数和组合。'
            '后四章保留二十道进阶题：墙辅助计数、状态与折返、嵌套图案和递归系统。'
            '每道进阶题都有参与路径约束的墙，逐步引入参数交换、递归返回、互递归、镜像与多层组合。'
            '每章先用小图形介绍新概念，再迁移到复杂图案。全部关卡开放，不锁进度。'
            '每题先显示目标，两条提示由玩家逐条展开。其他有效解同样被接受。\n\n'
            'byte 上限是经过引擎验证可达的练习预算，不声称是最优解长度，也不按数值大小代表难度。'
            '计分题的参考程序只在测试资源中，不进安装包；AI 提示词的公开教学示例使用独立棋盘。\n\n'
            '| 关卡 | 章节 | 名称 | 学习目标 | byte 上限 |\n| --- | --- | --- | --- | --- |\n'
        ) if language == 1 else (
            '# 30 original lessons\n\n'
            'These puzzles were independently designed from the public H language and board rules, '
            'not adapted from the community archive. Original layouts, names, objectives, hints, '
            'generation code and reference programs are released under MIT.\n\n'
            'Ten introductory lessons in two chapters cover movement and obstacles, then reuse, recursion, '
            'instruction arguments and composition. Only the first two fit a direct sequence of moves. Four advanced chapters retain twenty walled challenges: '
            'wall-assisted counting, state and return invariants, nested patterns and recursive systems. '
            'They introduce parameter swaps, recursive unwinding, mutual recursion, reflection and layered composition. '
            'Each new concept starts with a small example '
            'and is transferred to a larger pattern. All lessons are unlocked. Objectives appear '
            'first; two hints are revealed individually. Alternative valid solutions are welcome.\n\n'
            'Byte limits are verified achievable learning budgets, not claimed optimal scores or a '
            'numeric difficulty scale. Scored puzzle reference programs are test-only and excluded from app bundles; the AI prompt uses separate public teaching boards. '
            'Names, goals and hints are localized in English, Chinese and Japanese.\n\n'
            '| Lesson | Chapter | Name | Learning objective | Byte limit |\n| --- | --- | --- | --- | --- |\n'
        )
        retirement = ('v0.3.3 使用连续的 L01–L30。L07/L08 为重新设计的「旋转玫瑰」和「双灯相映」；其余棋盘保留。显示编号与内部存档 ID 分开，退役题记录与历史比赛快照继续保留。\n\n' if language == 1 else 'v0.3.3 uses continuous L01–L30 display numbers. L07/L08 are redesigned as Turning rose and Tandem lanterns; other boards are retained. Display numbers are separate from internal save IDs, and retired records and historical match snapshots remain readable.\n\n')
        intro = intro.replace('| Lesson |', retirement + '| Lesson |').replace('| 关卡 |', retirement + '| 关卡 |')
        for index, (problem, lesson) in enumerate(zip(problems, LESSONS + ADVANCED_LESSONS)):
            title, objective, _ = lesson
            intro += f"| {problem['id']} / L{problem['lesson']['order']:02} | {(CHAPTERS + ADVANCED_CHAPTERS)[index//5][language]} | {title[language]} | {objective[language]} | {problem['byteLimit']} |\n"
        intro += (
            '\n运行 `scripts/check.sh` 使用真实 H 编译器和游戏引擎逐题重放参考解，检查 byte 限制、'
            '棋盘、ID 隔离、三语文案与存档。App Store 题库仅来自 HerbertCore；两个发行版还链接不含题库的 HerbertBattlefield。社区数据位于可选模块 HerbertCommunity。\n\n'
            '参考解（含剧透）：[测试程序](../Tests/HerbertCoreTests/Fixtures/original-solutions.json)。'
            '设计源：[生成脚本](../scripts/generate_original_problems.py)。\n'
        ) if language == 1 else (
            '\n`scripts/check.sh` replays all references with the real H compiler and game engine, '
            'checking byte limits, boards, distinct IDs, translations and save compatibility. '
            'App Store puzzle resources come only from HerbertCore; both editions also link the resource-free HerbertBattlefield. The archive lives in optional HerbertCommunity.\n\n'
            'Spoilers: [test-only references](../Tests/HerbertCoreTests/Fixtures/original-solutions.json). '
            'Design source: [generator](../scripts/generate_original_problems.py).\n'
        )
        (ROOT/'docs'/filename).write_text(intro)


if __name__ == '__main__':
    generate()
