#!/usr/bin/env python3
"""Build 50 independently designed lessons, translations and test-only reference programs."""
import json
from pathlib import Path
import re
from advanced_course import CHAPTERS as ADVANCED_CHAPTERS, LESSONS as ADVANCED_LESSONS, advanced_designs

ROOT = Path(__file__).resolve().parents[1]
MARKER = '// Original curriculum — generated by scripts/generate_original_problems.py'
CHAPTERS = [
    ('Read the path', '读懂路径', '道筋を読む'),
    ('Plan around obstacles', '规划与避障', '障害物を避ける'),
    ('Name a repeated idea', '给重复命名', '繰り返しに名前を付ける'),
    ('Control recursion', '控制递归', '再帰を制御する'),
    ('Pass instructions', '传递指令', '命令を渡す'),
    ('Compose a small program', '组合成小程序', '小さなプログラムを組み立てる'),
]
# Each lesson adds one idea, then revisits it in a different spatial arrangement.
# Two hints move from observation to a strategy; full programs stay in test fixtures.
LESSONS = [
    (('First light', '第一盏灯', '最初の灯り'),
     ('Move one cell forward. The robot starts facing up.', '向前走一格。机器人开始时面向上方。', '一マス前へ進もう。ロボットは最初、上を向いています。'),
     [('The ring is directly ahead of the robot.', '圆环就在机器人的正前方。', '輪はロボットのすぐ前にあります。'),
      ('One s is one forward move.', '一个 s 就是向前走一步。', 's 一つで一歩前に進みます。')]),
    (('Four lanterns', '四盏路灯', '四つの灯り'),
     ('Count cells and light a straight row of four targets.', '数清格子，点亮直线上的四个目标。', 'マスを数えて、一直線の四つの目標を灯そう。'),
     [('Count the gaps between cell centers, not the grid lines.', '按格子中心之间的间隔数步数，不要数网格线。', '線ではなく、マスの中心の間隔を数えましょう。'),
      ('Write one s for each cell you need to move.', '需要走几格，就写几个 s。', '進むマスの数だけ s を書きましょう。')]),
    (('Right at the corner', '在拐角右转', '角で右へ'),
     ('Separate moving from turning: r turns without moving.', '区分前进与转向：r 只转向，不移动。', '移動と回転を区別しよう。r は向きだけを変えます。'),
     [('Reach the corner before turning.', '先走到拐角，再转向。', '角に着いてから曲がりましょう。'),
      ('After r, count the cells along the second segment.', '执行 r 后，再数第二段路径的格子。', 'r の後で、次の区間のマスを数えましょう。')]),
    (('A turn to the left', '向左转弯', '左へ曲がる'),
     ('Use l and keep track of the robot’s own heading.', '使用 l，并始终以机器人的朝向判断左右。', 'l を使い、ロボットの向きを基準に左右を考えよう。'),
     [('The first segment goes up; the second goes left.', '第一段向上，第二段向左。', '最初は上へ、次は左へ進みます。'),
      ('Turning costs a byte even though the position stays the same.', '转向时位置不变，但指令仍占一个 byte。', 'その場での回転も一 byte です。')]),
    (('Turn back', '回头看看', '振り返る'),
     ('Visit both sides of the start using a half turn.', '利用掉头，走到起点两侧的目标。', '半回転して、出発点の両側の目標を訪ねよう。'),
     [('After the upper target, face down and pass the start.', '到达上方目标后，朝下走，经过起点。', '上の目標の後、下を向いて出発点を通りましょう。'),
      ('Two consecutive l or r commands make a half turn.', '连续两个 l 或两个 r 就能掉头。', 'l または r を二回続けると半回転します。')]),
    (('Around the block', '绕过石墙', '壁を回り込む'),
     ('Plan a detour around a wall; blocked moves stay in place.', '绕过墙壁规划路线；撞墙时机器人会留在原地。', '壁を回り込もう。壁に向かって進んでも位置は変わりません。'),
     [('The direct route is blocked. Look to the right of the wall.', '直线路线被堵住了，观察墙的右侧。', '直進はできません。壁の右側を見ましょう。'),
      ('Try three segments: right, up, then left.', '把路线分成向右、向上、向左三段。', '右、上、左の三区間に分けてみましょう。')]),
    (('Two bends ahead', '连续两个弯', '二つの曲がり角'),
     ('Plan several waypoints before writing the whole route.', '先确定几个转折点，再写完整路线。', 'いくつかの通過点を決めてから、道筋を書こう。'),
     [('Follow the targets through the two rising corners.', '沿目标经过两个向上的拐角。', '目標をたどって、上へ続く二つの角を通りましょう。'),
      ('Alternate a right turn and a left turn to face up again.', '交替使用右转和左转，可以重新朝上。', '右と左を交互に使うと、再び上を向けます。')]),
    (('Keep the lights', '守住亮光', '灯りを守る'),
     ('Avoid a trap so the targets you already lit stay lit.', '避开陷阱，让已经点亮的目标保持亮起。', '罠を避けて、灯した目標を消さずに進もう。'),
     [('The marked trap lies between the two targets.', '带 × 的陷阱位于两个目标之间。', '二つの目標の間に × の罠があります。'),
      ('After the lower target, detour two cells to the right.', '到达下方目标后，向右绕开两格。', '下の目標の後、右へ二マス迂回しましょう。')]),
    (('Light it again', '重新点亮', 'もう一度灯す'),
     ('Recover from a trap by revisiting any target it erased.', '踩到陷阱后，重新经过被熄灭的目标也能完成。', '罠で消えた目標も、もう一度訪れれば灯せます。'),
     [('A trap clears all lit targets, not just the nearest one.', '陷阱会清空全部已点亮目标，不只影响附近的目标。', '罠は近くの目標だけでなく、灯した全目標を消します。'),
      ('A loop can visit the lower target again after the upper one.', '可以走一圈，在上方目标之后重新经过下方目标。', '一周すれば、上の目標の後で下の目標を再訪できます。')]),
    (('Perimeter patrol', '沿边巡游', '外周を一巡'),
     ('Combine counting and turns to patrol a square boundary.', '结合步数与转向，沿正方形边缘巡游。', '歩数と回転を組み合わせ、正方形の外周を巡ろう。'),
     [('Each side has the same length.', '每一条边的长度相同。', 'どの辺も同じ長さです。'),
      ('Write one side and a right turn, then repeat that pattern.', '先写一条边和一次右转，再重复这个模式。', '一辺と右回転を書き、その形を繰り返しましょう。')]),
    (('A name for three steps', '为三步取名', '三歩に名前を付ける'),
     ('Name three steps as a procedure and call it repeatedly.', '把三步定义成一个过程，再反复调用。', '三歩を手続きにして、繰り返し呼び出そう。'),
     [('The byte limit is shorter than the full straight route.', 'byte 限制比直接写完这条直线所需的代码更短。', '全歩数を書き並べると byte 制限を超えます。'),
      ('Declare a:sss on one line; call a on the final line.', '在一行声明 a:sss，在最后一行调用 a。', '一行に a:sss と宣言し、最後の行で a を呼びましょう。')]),
    (('Square stamp', '方形印章', '四角いスタンプ'),
     ('Reuse a side-and-turn procedure four times.', '把走一边再转向的过程重复四次。', '一辺を進んで曲がる手続きを四回使おう。'),
     [('The four sides share one movement pattern.', '四条边共用同一段动作。', '四辺とも同じ動きです。'),
      ('Put the right turn inside the procedure, after the steps.', '把右转放进过程里，接在前进指令后面。', '手続きの中で、歩く命令の後に右回転を入れましょう。')]),
    (('Stair tiles', '阶梯砖块', '階段のタイル'),
     ('Find a repeated stair tile that ends facing up.', '找出一个重复阶梯单元，让它结束时仍朝上。', '最後に上を向く、階段の繰り返し単位を見つけよう。'),
     [('Each tile rises two cells and moves right two cells.', '每个单元向上两格，再向右两格。', '一単位で上へ二マス、右へ二マス進みます。'),
      ('Use a right turn to go across and a left turn to face up.', '右转后横走，再左转恢复朝上。', '右回転で横へ進み、左回転で上向きに戻しましょう。')]),
    (('Four compass arms', '四向罗盘', '四方向の腕'),
     ('Make an out-and-back procedure rotate toward the next arm.', '让往返过程结束时转向下一条分支。', '往復する手続きの最後で、次の腕の方向を向こう。'),
     [('Every arm starts from the center.', '每条分支都从中心出发。', 'どの腕も中心から始まります。'),
      ('Go out, turn back, return, then turn toward the next arm.', '走出去、掉头、回中心，再转向下一条分支。', '進み、半回転し、中心に戻り、次の方向へ回りましょう。')]),
    (('Rhythm within rhythm', '节奏中的节奏', 'リズムの中のリズム'),
     ('Group repeated procedure calls into a second procedure.', '把重复的过程调用再组合成第二个过程。', '手続きの繰り返しを、別の手続きにまとめよう。'),
     [('There are nine identical stair tiles.', '这里有九个相同的阶梯单元。', '同じ階段の単位が九つあります。'),
      ('Three groups of three calls use fewer bytes than nine calls.', '把三次调用组成一组，再调用三组，比写九次调用更短。', '三回を一組にして三組呼ぶと、九回並べるより短くなります。')]),
    (('A self-repeating stair', '自动延伸的阶梯', '自分を呼ぶ階段'),
     ('Use a procedure that calls itself after one stair tile.', '每完成一个阶梯单元，就让过程再次调用自己。', '階段を一単位進んだ後で、同じ手続きを呼ぼう。'),
     [('The route repeats without changing its shape.', '路线一直重复同一种形状。', '道筋は同じ形を繰り返します。'),
      ('Put a call to a at the end of a; completion stops execution.', '在 a 的末尾调用 a；全部目标亮起时游戏会停止执行。', 'a の末尾で a を呼びましょう。全目標が灯れば実行は止まります。')]),
    (('A counted corner', '数得清的拐角', '歩数を決めた角'),
     ('Use a numeric parameter to walk two different distances.', '用数值参数控制两段不同长度的前进。', '数値引数で、長さの違う二区間を歩こう。'),
     [('One segment is seven cells; the other is four.', '一段长七格，另一段长四格。', '一区間は七マス、もう一区間は四マスです。'),
      ('A recursive step counter can subtract 1 until the call is skipped.', '递归计步过程每次减 1，直到参数非正而跳过调用。', '再帰の歩数を毎回 1 減らすと、非正の値で呼び出しが省略されます。')]),
    (('Rectangle recipe', '长方形配方', '長方形のレシピ'),
     ('Compose a rectangle from one reusable counted walk.', '用一个可复用的计步过程拼出长方形。', '歩数を指定する一つの手続きで、長方形を作ろう。'),
     [('The long side is eight cells and the short side is four.', '长边八格，短边四格。', '長い辺は八マス、短い辺は四マスです。'),
      ('Group a long side and a short side, then use that group twice.', '把一条长边和一条短边组成一组，再用两次。', '長辺と短辺を一組にして、二回使いましょう。')]),
    (('Growing spiral', '生长的螺旋', '伸びるらせん'),
     ('Increase a numeric distance after each right turn.', '每次右转后，把下一段的长度增加一格。', '右へ曲がるたびに、次の区間を一マス長くしよう。'),
     [('The segment lengths are 1, 2, 3, and so on.', '各段长度依次为 1、2、3……', '各区間の長さは 1、2、3……です。'),
      ('Separate the counted walk from the recursive spiral.', '把计步过程与螺旋递归过程分开。', '歩数を数える手続きと、らせんの再帰を分けましょう。')]),
    (('Descending staircase', '逐级缩短', '短くなる階段'),
     ('Walk equal vertical and horizontal legs, then reduce both.', '每级先走等长的纵横两段，再缩短下一级。', '縦と横を同じ長さだけ進み、次の段を短くしよう。'),
     [('The stair lengths shrink from six to one.', '阶梯长度从六格逐渐缩短到一格。', '階段の長さは六マスから一マスへ減ります。'),
      ('Pass X to both legs and X-1 to the next stair call.', '两段都使用 X，把 X-1 传给下一次阶梯调用。', '両区間に X を使い、次の階段には X-1 を渡しましょう。')]),
    (('Pass a pattern', '把图案传进去', '模様を引数に'),
     ('Pass a side-and-turn instruction sequence as a parameter.', '把走一边再转向的指令串作为参数传入。', '一辺と回転の命令列を、引数として渡そう。'),
     [('A parameter can represent instructions instead of a number.', '参数除了数值，也可以代表一串指令。', '引数は数値だけでなく、命令列にもなれます。'),
      ('A body containing XXXX executes the supplied sequence four times.', '过程体中的 XXXX 会把传入的指令串执行四次。', '本体の XXXX は、渡された命令列を四回実行します。')]),
    (('A reusable repeater', '通用重复器', '汎用の繰り返し'),
     ('Combine a repetition count with an instruction parameter.', '把重复次数与指令参数组合起来。', '回数と命令列の引数を組み合わせよう。'),
     [('Use one parameter for six repeats and another for a stair tile.', '一个参数表示重复六次，另一个表示阶梯单元。', '一つの引数を六回の繰り返しに、もう一つを階段の単位に使いましょう。'),
      ('Execute Y, then call the repeater with X-1 and the same Y.', '执行 Y，再用 X-1 和同一个 Y 调用重复器。', 'Y を実行し、X-1 と同じ Y で繰り返しを呼びましょう。')]),
    (('Alternating rows', '来回的灯带', '交互の灯りの列'),
     ('Alternate two instruction patterns to sweep parallel rows.', '交替执行两种指令模式，扫过平行的灯带。', '二つの命令パターンを交互に使い、平行な列を巡ろう。'),
     [('One row turns right twice; the next turns left twice.', '一行结束时连续两次右转，下一行则两次左转。', '一列の終わりでは右へ二回、次の列では左へ二回曲がります。'),
      ('Swap instruction parameters when recursively calling the next row.', '递归到下一行时，交换两个指令参数。', '次の列を再帰で呼ぶとき、二つの命令引数を交換しましょう。')]),
    (('A growing thread', '不断加长的线', '伸び続ける糸'),
     ('Grow an instruction parameter by appending two steps.', '每次在指令参数后追加两步，让路径逐渐增长。', '命令引数の末尾に二歩を足して、道筋を伸ばそう。'),
     [('This spiral turns left and has lengths 2, 4, 6, and so on.', '这条螺旋每次左转，各段长 2、4、6……', 'このらせんは左へ曲がり、長さが 2、4、6……と増えます。'),
      ('Execute X, turn left, then pass Xss into the next call.', '执行 X、左转，再把 Xss 传给下一次调用。', 'X を実行して左へ曲がり、次の呼び出しに Xss を渡しましょう。')]),
    (('Expanding compass', '伸展的罗盘', '広がるコンパス'),
     ('Reuse a growing instruction sequence for both outward and return travel.', '用同一个逐渐增长的指令串完成出发与返回。', '伸びる同じ命令列を、往路と復路の両方に使おう。'),
     [('Return to the center before exploring the next direction.', '探索下一个方向前，先回到中心。', '次の方向へ進む前に、中心に戻りましょう。'),
      ('Execute X twice with a half turn between them, then grow X.', '两次执行 X，中间掉头，然后给 X 增加一步。', 'X を二回、間に半回転を挟んで実行し、その後 X を一歩伸ばしましょう。')]),
    (('Twin towers', '双塔灯光', '二つの塔'),
     ('Combine a counted walk, a return trip and a connecting bridge.', '组合计步、原路返回和连接两侧的桥。', '歩数指定、折り返し、二つの塔を結ぶ橋を組み合わせよう。'),
     [('The trap row makes crossing between the towers unsafe.', '两塔中间的一排陷阱让横穿变得危险。', '塔の間の罠の列は、横切ると危険です。'),
      ('Finish one tower, return to the bottom, then cross to the other.', '先走完一座塔，返回底部，再横走到另一座。', '一つの塔を終え、下に戻ってから、もう一つへ渡りましょう。')]),
    (('Woven field', '编织灯田', '織りなす灯り'),
     ('Use a finite row count and alternate the connector’s turn direction.', '用有限的行数控制灯田，并交替改变连接处的转向。', '有限の行数を使い、接続部分の回転方向を交互に変えよう。'),
     [('Each row is eight cells long; safe connectors are at the ends.', '每行长八格，安全的连接处在两端。', '各列は八マスで、安全な接続部分は両端にあります。'),
      ('Adding rr to a turn parameter switches its effective direction.', '给转向参数增加 rr，可以切换它实际的转向方向。', '回転の引数に rr を足すと、実際の回転方向が切り替わります。')]),
    (('Rising comb', '向上生长的梳齿', '伸びる櫛の歯'),
     ('Grow each branch, return to the baseline, then shift one cell.', '让每根分支增长，返回基线后横移一格。', '枝を伸ばし、基線に戻ってから一マス横へ移ろう。'),
     [('The teeth have lengths 1 through 9 and share a baseline.', '梳齿长度从 1 到 9，共用一条基线。', '歯の長さは 1 から 9 で、基線を共有します。'),
      ('Reuse the same counted walk outward and back; restore the heading.', '出发与返回复用同一个计步过程，并恢复原朝向。', '往復に同じ歩数指定を使い、最後に向きを元に戻しましょう。')]),
    (('Nested windows', '层叠的窗', '重なる窓'),
     ('Nest a counted walk inside a fourfold instruction repeater.', '把计步前进嵌套进重复四次的指令参数中。', '歩数指定を、命令列を四回繰り返す手続きに入れよう。'),
     [('Four squares share a corner; their side lengths are 3, 6, 9 and 12.', '四个正方形共用一个角，边长分别为 3、6、9、12。', '四つの正方形が一つの角を共有し、辺の長さは 3、6、9、12 です。'),
      ('A square can repeat the instruction “walk X, turn right” four times.', '一个正方形就是把「走 X 步，再右转」重复四次。', '正方形は「X 歩進んで右回転」を四回繰り返す形です。')]),
    (('Clockwork garden', '发条花园', 'からくりの庭'),
     ('Combine counted repetition, shrinking squares and fourfold rotation.', '组合计数重复、逐渐缩小的正方形与四向旋转。', '回数指定、縮む正方形、四方向の回転を組み合わせよう。'),
     [('Each quadrant contains squares with sides 6, 4 and 2.', '每个象限中都有边长为 6、4、2 的正方形。', '各象限に、辺が 6、4、2 の正方形があります。'),
      ('Build one square, recurse with X-2, then rotate the whole motif.', '先构造一个正方形，再用 X-2 递归，最后旋转整个图案。', '正方形を作って X-2 で再帰し、模様全体を回転させましょう。')]),
]


def s(count):
    return 's' * count


def square(size):
    return (s(size) + 'r') * 4


def trace(start, commands, walls=(), bounded=True):
    x, y = start
    heading = 0
    points = []
    for command in commands:
        if command == 's':
            dx, dy = [(0, -1), (1, 0), (0, 1), (-1, 0)][heading]
            nx, ny = x + dx, y + dy
            if (nx, ny) not in walls:
                if bounded:
                    assert 0 <= nx < 25 and 0 <= ny < 25, (start, nx, ny)
                x, y = nx, ny
            points.append((x, y))
        else:
            heading = (heading + (1 if command == 'r' else -1)) % 4
    return points


def designs():
    # Explicit primitive routes provide an independent oracle for the H reference programs.
    return [
        ((12, 13), 's', 's', None, [], []),
        ((12, 17), s(4), s(4), None, [], []),
        ((10, 16), s(3)+'r'+s(3), s(3)+'r'+s(3), [(10, 13), (13, 13)], [], []),
        ((15, 17), s(3)+'l'+s(4), s(3)+'l'+s(4), [(15, 14), (11, 14)], [], []),
        ((12, 12), 'ssrrssss', 'ssrrssss', [(12, 10), (12, 14)], [], []),
        ((12, 14), 'rsslsslss', 'rsslsslss', [(12, 12)], [(11, 13), (12, 13), (13, 13)], []),
        ((7, 20), 'sssrssslsssrsss', 'sssrssslsssrsss', None,
         [(8, 18), (9, 18), (8, 16), (11, 15), (12, 15)], []),
        ((12, 17), 'ssrsslsssslss', 'ssrsslsssslss', [(12, 15), (12, 11)], [(12, 12)], [(12, 13)]),
        ((10, 16), 'ssssrssssrssrssss', 'ssssrssssrssrssss', [(10, 14), (14, 12)],
         [(11, 13), (12, 13), (13, 13)], [(10, 12)]),
        ((8, 18), square(6), square(6), None, [(x, y) for y in range(13, 18) for x in range(9, 14)], []),
        ((12, 21), s(18), 'a:sss\naaaaaa', None, [], []),
        ((10, 17), square(4), 'a:ssssr\naaaa', None, [], []),
        ((7, 21), 'ssrssl'*5, 'a:ssrssl\naaaaa', None, [], []),
        ((12, 12), (s(3)+'rr'+s(3)+'r')*4, 'a:sssrrsssr\naaaa', None, [], []),
        ((3, 21), 'ssrssl'*9, 'a:ssrssl\nb:aaa\nbbb', None, [], []),
        ((8, 21), 'srsl'*8, 'a:srsla\na', None, [], []),
        ((8, 20), s(7)+'r'+s(4), 'a(X):sa(X-1)\na(7)ra(4)', None, [], []),
        ((9, 21), (s(8)+'r'+s(4)+'r')*2, 'a(X):sa(X-1)\nb:a(8)ra(4)r\nbb', None, [], []),
        ((12, 12), ''.join(s(n)+'r' for n in range(1, 10)), 'b(X):sb(X-1)\na(X):b(X)ra(X+1)\na(1)', None, [], []),
        ((2, 23), ''.join(s(n)+'r'+s(n)+'l' for n in range(6, 0, -1)),
         'b(X):sb(X-1)\na(X):b(X)rb(X)la(X-1)\na(6)', None, [], []),
        ((10, 17), square(3), 'a(X):XXXX\na(sssr)', None, [], []),
        ((6, 21), 'ssrssl'*6, 'a(X,Y):Ya(X-1,Y)\na(6,ssrssl)', None, [], []),
        ((8, 6), 'r'+''.join(s(6)+('rssr' if n % 2 == 0 else 'lssl') for n in range(6)),
         'a(X,Y):Xa(Y,X)\nra(ssssssrssr,sssssslssl)',
         [(x, y) for y in range(6, 17, 2) for x in range(8, 15)], [], []),
        ((12, 12), ''.join(s(n)+'l' for n in range(2, 19, 2)), 'a(X):Xla(Xss)\na(ss)', None, [], []),
        ((12, 12), ''.join(s(n)+'rr'+s(n)+'l' for n in range(1, 9)), 'a(X):XrrXla(Xs)\na(s)', None, [], []),
        ((8, 21), s(10)+'rr'+s(10)+'l'+s(8)+'l'+s(10),
         'a(X,Y):Ya(X-1,Y)\nb:a(10,s)\nbrrbla(8,s)lb', None, [], [(x, 15) for x in range(9, 16)]),
        ((8, 6), 'r'+''.join(s(8)+(('rr'*n+'r')+s(2)+('rr'*n+'r') if n < 4 else '') for n in range(5)),
         'b(X):sb(X-1)\na(X,Y):b(8)Yb(2)Ya(X-1,rrY)\nra(5,r)', None, [],
         [(x, y) for y in range(7, 14, 2) for x in range(9, 16)]),
        ((4, 21), ''.join(s(n)+('rr'+s(n)+'lsl' if n < 9 else '') for n in range(1, 10)),
         'b(X):sb(X-1)\na(X):b(X)rrb(X)lsla(X+1)\na(1)', None, [], [(x, 22) for x in range(4, 14)]),
        ((6, 21), ''.join(square(n) for n in (3, 6, 9, 12)),
         'a(X,Y):Ya(X-1,Y)\nb(X):a(4,a(X,s)r)\nb(3)b(6)b(9)b(12)', None, [], []),
        ((12, 12), (''.join(square(n) for n in (6, 4, 2))+'r')*4,
         'a(X,Y):Ya(X-1,Y)\nb(X):a(4,a(X,s)r)\nc(X):b(X)c(X-2)\nd:c(6)r\ndddd', None,
         [(x, y) for y in range(5, 20) for x in range(5, 20) if x in (5, 19) or y in (5, 19)],
         [(x, y) for y in range(7, 18, 2) for x in range(7, 18, 2)]),
    ]


def reference_outcome(start, commands, path, targets, traps):
    """Replay the explicit geometric oracle only until its last target is lit."""
    position, heading, lit, blocked, resets = start, 0, set(), 0, 0
    moves = iter(path)
    for steps, command in enumerate(commands, 1):
        if command == 's':
            next_position = next(moves)
            if next_position == position:
                blocked += 1
            else:
                position = next_position
                if position in traps:
                    lit.clear()
                    resets += 1
                if position in targets:
                    lit.add(position)
        else:
            heading = (heading + (1 if command == 'r' else -1)) % 4
        if lit == targets:
            return dict(steps=steps, blocked=blocked, traps=resets,
                        endPosition=list(position), endHeading=heading)
    raise ValueError(f'Geometric oracle did not complete from {start}')


def generate():
    translations = [{} for _ in range(3)]

    def localize(values):
        for language, text in enumerate(values):
            translations[language][values[0]] = text
        return values[0]

    problems, solutions = [], []
    all_lessons = LESSONS + ADVANCED_LESSONS
    all_designs = designs() + advanced_designs(trace)
    all_chapters = CHAPTERS + ADVANCED_CHAPTERS
    assert len(all_lessons) == len(all_designs) == 50
    for index, ((title, objective, hints), design) in enumerate(zip(all_lessons, all_designs), 1):
        start, commands, source, targets, walls, traps = design
        path = trace(start, commands, set(walls))
        targets = set(path if targets is None else targets) - {start} - set(traps)
        assert targets and not (set(path) & set(walls))
        assert targets <= set(path) and not (targets & set(walls))
        rows = [['.'] * 25 for _ in range(25)]
        for cells, symbol in [(walls, 'x'), (traps, '*'), (targets, 'o'), ([start], 'u')]:
            for x, y in cells:
                rows[y][x] = symbol
        chapter = (index-1)//5
        problems.append(dict(id=10000+index, title=localize(title), author='Herbert',
                             byteLimit=len(re.findall(r'[A-Za-z]|[0-9]+', source)),
                             sourceURL='', sourceSHA256='', rows=[''.join(row) for row in rows],
                             lesson=dict(order=index, chapter=chapter+1, chapterTitle=localize(all_chapters[chapter]),
                                         objective=localize(objective), hints=[localize(hint) for hint in hints])))
        solutions.append(dict(id=10000+index, source=source,
                              **reference_outcome(start, commands, path, targets, set(traps))))
    assert len(problems) == 50 and len({tuple(p['rows']) for p in problems}) == 50
    (ROOT/'Sources/HerbertCore/Resources/original-problems.json').write_text(json.dumps(problems, ensure_ascii=False, indent=2)+'\n')
    (ROOT/'Tests/HerbertCoreTests/Fixtures/original-solutions.json').write_text(json.dumps(solutions, indent=2)+'\n')
    for language, values in zip(['en', 'zh-Hans', 'ja'], translations):
        path = ROOT/f'Sources/HerbertCore/Resources/{language}.lproj/Localizable.strings'
        original = path.read_text().split(MARKER)[0].rstrip()
        lines = [f'{json.dumps(k, ensure_ascii=False)} = {json.dumps(v, ensure_ascii=False)};' for k, v in values.items()]
        path.write_text(original+'\n\n'+MARKER+'\n'+'\n'.join(lines)+'\n')
    write_docs(problems)
    print('Generated 50 original lessons, three languages, and test-only reference solutions.')


def write_docs(problems):
    for language, filename in [(0, 'original-course.md'), (1, 'original-course.zh-CN.md')]:
        intro = (
            '# 50 道原创学习关卡\n\n'
            '这套课程依据公开的 H 语言与棋盘规则独立设计，没有把社区棋盘改名或改图后使用。'
            '原创布局、名称、学习目标、提示、生成脚本与参考程序随项目以 MIT 许可发布。\n\n'
            '前六章各五题：先理解一步与朝向，再处理障碍；随后学习复用、递归、指令参数和组合。'
            '后四章新增二十道进阶题：墙辅助计数、状态与折返、嵌套图案和递归系统。'
            '每道进阶题都有参与路径约束的墙，逐步引入参数交换、递归返回、互递归、镜像与多层组合。'
            '每章先用小图形介绍新概念，再迁移到复杂图案。全部关卡开放，不锁进度。'
            '每题先显示目标，两条提示由玩家逐条展开。其他有效解同样被接受。\n\n'
            'byte 上限是经过引擎验证可达的练习预算，不声称是最优解长度，也不按数值大小代表难度。'
            '参考程序只在测试资源中，安装包不含答案。\n\n'
            '| 关卡 | 章节 | 名称 | 学习目标 | byte 上限 |\n| --- | --- | --- | --- | --- |\n'
        ) if language == 1 else (
            '# 50 original lessons\n\n'
            'These puzzles were independently designed from the public H language and board rules, '
            'not adapted from the community archive. Original layouts, names, objectives, hints, '
            'generation code and reference programs are released under MIT.\n\n'
            'The first six chapters move from orientation and obstacles to reuse, recursion, '
            'instruction arguments and composition. Four advanced chapters add twenty walled challenges: '
            'wall-assisted counting, state and return invariants, nested patterns and recursive systems. '
            'They introduce parameter swaps, recursive unwinding, mutual recursion, reflection and layered composition. '
            'Each new concept starts with a small example '
            'and is transferred to a larger pattern. All lessons are unlocked. Objectives appear '
            'first; two hints are revealed individually. Alternative valid solutions are welcome.\n\n'
            'Byte limits are verified achievable learning budgets, not claimed optimal scores or a '
            'numeric difficulty scale. Reference programs are test-only and excluded from app bundles. '
            'Names, goals and hints are localized in English, Chinese and Japanese.\n\n'
            '| Lesson | Chapter | Name | Learning objective | Byte limit |\n| --- | --- | --- | --- | --- |\n'
        )
        for index, (problem, lesson) in enumerate(zip(problems, LESSONS + ADVANCED_LESSONS)):
            title, objective, _ = lesson
            intro += f"| {problem['id']} / L{index+1:02} | {(CHAPTERS + ADVANCED_CHAPTERS)[index//5][language]} | {title[language]} | {objective[language]} | {problem['byteLimit']} |\n"
        intro += (
            '\n运行 `scripts/check.sh` 使用真实 H 编译器和游戏引擎逐题重放参考解，检查 byte 限制、'
            '棋盘、ID 隔离、三语文案与存档。App Store 题库仅来自 HerbertCore；两个发行版还链接不含题库的 HerbertBattlefield。社区数据位于可选模块 HerbertCommunity。\n\n'
            '参考解（含剧透）：[测试程序](../Tests/HerbertCoreTests/Fixtures/original-solutions.json)。'
            '设计源：[生成脚本](../scripts/generate_original_problems.py)。\n'
        ) if language == 1 else (
            '\n`scripts/check.sh` replays all references with the real H compiler and game engine, '
            'checking byte limits, boards, distinct IDs, translations and save compatibility. '
            'App Store puzzle resources come only from HerbertCore; both editions also link the resource-free HerbertBattlefield. The archive lives in optional HerbertCommunity.\n\n'
            'Spoilers: [test-only references](../Tests/HerbertCoreTests/Fixtures/original-solutions.json). '
            'Design source: [generator](../scripts/generate_original_problems.py).\n'
        )
        (ROOT/'docs'/filename).write_text(intro)


if __name__ == '__main__':
    generate()
